Externals.cfg
Currently the workflow fails on hera at the make_ics and/or make_lbcs step because the wgrib2 module is not loaded. A PR was accepted in regional_workflow to fix this problem, but the hash was never updated here in the top-level app. This change updates regional_workflow to 9b32ce314, which includes the relevant bug fix.
Ran the test suite on Hera...all pre-processing steps are now successful, although there are some known failures in the forecast step (regional_003, regional_004, and regional_010) that will be addressed in a follow-up PR.
=> Update hash for regional_workflow to latest fix that runs on Hera

manage_externals/.gitignore, manage_externals/.travis.yml, manage_externals/manic/checkout.py, manage_externals/manic/externals_description.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_unit_externals_description.py
Updates manage_externals to the most recent release which includes a critical Python 3+ bug fix and supports 3.7 and 3.8.  This new version avoids the previous incompatibility between manage_externals and the YAML namelist generation/Jinja templating for XML and diag_table files.  Users will no longer have to load different versions of Python in-between manage_externals and running the workflow.
Tested successfully on Hera.  All repos are cloned correctly.  @JulieSchramm tested on Cheyenne.
=> Update manage_externals for Python 3+ bug fix, support for 3.7 and 3.8

Externals.cfg, src/build_forecast.sh
This PR must be merged simultaneously with PR#[287](https://github.com/NOAA-EMC/regional_workflow/pull/287) into NOAA-EMC/regional_workflow.
Summary of Modifications:
------------------------
* In Externals.cfg:
* Update the source of the ufs_weather_app external to be the release/public-v2 branch of the ufs-community/ufs-weather-model repo (which is the authoritative repo).
* Update the regional_workflow external so it points to the HEAD of the develop branch of the NOAA-EMC/regional_workflow repo.
* In build_forecast.sh, add the suites FV3_GFS_2017_gfdlmp_regional and FV3_RRFS_v1beta to the list of suites for which to build the forecast model.
=> Update source of ufs_weather_model to be the release/public-v2 branch of authoritative repo; update physics suites for which to build FV3

Externals.cfg
Set branch of regional_workflow in Externals.cfg to release/public-v1.
None
None
=> Change branch of regional_workflow from develop to release/public-v1.

src/build_all.sh, src/build_post.sh, src/install_all.sh
* Remove hard-coded executable directory names by replacing them with the new variable BIN_DIR that gets set only in one place.
* This removes the bug where an empty "exec" directory is created in addition to the "bin" directory in which the executables are placed.
Built on hera successfully.  The executables are identical to the ones created before these changes, and an empty "exec" directory is no longer created.
=> Remove hard-coded executables directory names

src/machine-setup.sh
Change `src/machine-setup.sh` so that no `module purge` is done on gaea, or hell will break loose.
This PR is for the upcoming SRW App public release 1.0, not sure to which branch should go to. 
A corresponding PR is required for UFS_UTILS (https://github.com/NOAA-EMC/UFS_UTILS/pull/189). There is also an update for the ufs-weather-model, which will be part of this PR (not yet): https://github.com/ufs-community/ufs-weather-model/pull/248
=> src/machine-setup.sh: don't purge on gaea

CMakeLists.txt, Externals.cfg, docs/README_cheyenne_gnu.txt, docs/README_cheyenne_intel.txt, src/CMakeLists.txt
This PR fixes a number of issues with building the latest version of the ufs-weather-model and supersedes https://github.com/ufs-community/ufs-srweather-app/pull/48. It also fixes https://github.com/ufs-community/ufs-srweather-app/issues/49.
Changes:
- Use fixed hash instead of branch for ufs-weather-model in Externals.cfg
- CMakeLists.txt: cmake 3.15 is required by the submodules
- src/CMakeLists.txt: update CCPP suites
- Update documentation for cheyenne.intel and cheyenne.gnu
- Also: convert tabs in various `CMakeLists.txt` files into spaces and remove unnecessary CMake modules import (this directory doesn't exist)
This has been tested successfully on Cheyenne with the Intel compiler. Somebody else should try to test this with GNU on Cheyenne, and on other platforms if possible.
=> release/public-v1: fix Cheyenne build, update CCPP suites etc

Externals.cfg
This latest release builds only the executables needed by the SRW App.
Built on Cheyenne with Intel and GNU compilers.  Intel out-of-the-box case workflow runs to completion, a fix to run with the GNU build is in PR "https://github.com/NOAA-EMC/regional_workflow/pull/363"
=> Update hash for ufs_utils to point to latest version of release/public-v2

devbuild.sh, docs/README_orion_intel.txt
Per discussion on #45, adding a build script for developer use. This will not be supported for community use, but limited to official platforms for testing purposes.
The build script should be invoked with the platform name and compiler as arguments, and works by sourcing the README files in the docs/ directory that describe the environment setup for each platform.
The README file for Orion also needed to be updated due to a change in the NCEPLIBS location to a more official spot.
Built successfully on Cheyenne (gnu, intel) and Orion (intel). Should work for any platform with the appropriate README_[platform]_[compiler].txt file.
=> Add build script for developers, update Orion NCEPLIBS location

Externals.cfg, src/CMakeLists.txt
This PR should be merged at the same time as PR #[361](https://github.com/NOAA-EMC/regional_workflow/pull/361) into regional_workflow:release/public-v1.
* Change the hashes in Externals.cfg to be those of the current HEADs of the release branches of the regional_workflow UFS_UTILS, ufs-weather-model, and EMC_post repos.
* Add the RRFS_v1alpha suite to and remove the RRFS_v1beta suite from the list of suites for which to build the forecast model code.
See PR #[361](https://github.com/NOAA-EMC/regional_workflow/pull/361).
=> Add the RRFS_v1alpha suite to the list of suites to build for

docs/README_cheyenne_intel.txt, docs/README_orion_intel.txt, docs/UsersGuide/requirements.txt
- Modify README_cheyenne_intel.txt to build with Intel
- Use older version of sphinx-bibtex 1.0.0, since latest release 2.0.0 is incompatible and ReadTheDocs build fails.
- Modify README_orion_intel.txt to build with intel
Intel build on Cheyenne works, GNU build does not.
=> master Fix Intel build on Cheyenne and ReadTheDocs build

Externals.cfg, docs/README_wcoss_cray_intel.txt, docs/README_wcoss_dell_p3_intel.txt
Added the build-environment files ('README_xxx.txt') for WCOSS Dell and Cray to the 'docs/' directory.
SRW App ('release/public-v1' branch) was built without any issues on WCOSS Dell and Cray.
Fixes issue mentioned in #79.
Related to https://github.com/NOAA-EMC/regional_workflow/pull/385.
@BenjaminBlake-NOAA
=> release/public-v1: port to WCOSS Dell and Cray

Externals.cfg
Update hash of regional_workflow in Externals.cfg to use the latest tested version corresponding to PR #[404](https://github.com/NOAA-EMC/regional_workflow/pull/404) into regional_workflow.
See PR #[404](https://github.com/NOAA-EMC/regional_workflow/pull/404) into regional_workflow.
=> Update hash of regional_workflow in Externals.cfg to use the latest tested version (corresponding to PR #404 into regional_workflow)

Externals.cfg, docs/UsersGuide/source/Quickstart.rst, docs/UsersGuide/source/SRWAppOverview.rst, env/build_cheyenne_gnu.env
Updating Cheyenne build environment to use GNU 10.1. This requires updating the weather model hash to include a fix for GNU 10 compilers.
Also took the opportunity to update the documentation to include the new location of the Cheyenne python environment.
Ran suite of release branch tests (minus the 3km versions) in [regional_workflow/tests/testlist.release_public_v1.txt](https://github.com/NOAA-EMC/regional_workflow/blob/develop/tests/testlist.release_public_v1.txt) with new GNU compilers. All passed. Also ran same tests on Hera as a sanity check (especially since the weather model hash was updated); all passed.
Resolves #81
=> Update weather model hash, upgrade Cheyenne GNU build environment to version 10.1

Externals.cfg
Update hash of regional_workflow in Externals.cfg to use the latest tested version corresponding to PR #[414](https://github.com/NOAA-EMC/regional_workflow/pull/414) into regional_workflow.
See PR #[414](https://github.com/NOAA-EMC/regional_workflow/pull/414) into regional_workflow.
=> Update hash of regional_workflow to use the latest tested version (corresponding to PR #414 into regional_workflow)

Externals.cfg, devbuild.sh
This PR should be merged right after PR #[416](https://github.com/NOAA-EMC/regional_workflow/pull/416) into regional_workflow (and using in Externals.cfg the hash of regional_workflow that the merge of PR #[416](https://github.com/NOAA-EMC/regional_workflow/pull/416) generates).
* Update hashes of regional_workflow and ufs-weather-model to work with PR #[416](https://github.com/NOAA-EMC/regional_workflow/pull/416) into regional_workflow.
* Fix devbuild.sh to work with new .env files (instead of old README files).
See PR #[416](https://github.com/NOAA-EMC/regional_workflow/pull/416) in regional_workflow.
=> Update hashes; fix devbuild.sh

Externals.cfg, src/CMakeLists.txt
This PR should be merged right after PR #[382](https://github.com/NOAA-EMC/regional_workflow/pull/382) into regional_workflow (and using in Externals.cfg the hash of regional_workflow that the merge of PR #[382](https://github.com/NOAA-EMC/regional_workflow/pull/382) generates).
* Add the FV3_HRRR suite to the list of suites to build.
* Update hashes of regional_workflow and ufs-weather-model to work with PR #[382](https://github.com/NOAA-EMC/regional_workflow/pull/382) into regional_workflow.
See PR #[382](https://github.com/NOAA-EMC/regional_workflow/pull/382) in regional_workflow.
=> Add the FV3_HRRR suite to build; update regional_workflow hash

Externals.cfg
This PR
- updates the hash of UFS_UTILS to point to the head of release/public-v2. Without this update, generating ICs crashes on gaea. The differences for UFS_UTILS can be viewed by checking out the current and new hash: there are large differences in `surface.F90` and a one-liner change in `build_all.sh`
- updates the hash of ufs-weather-model for the recent merge that fixes the b4b mismatches when changing the MPI decomposition for regional runs
- updates the hash of regional_workflow for the changes described in https://github.com/NOAA-EMC/regional_workflow/pull/429
- workflow (GST) runs end to end on gaea; note: do *not* use cron to automatically resubmit jobs
- no other systems tested yet
- waiting on https://github.com/NOAA-EMC/regional_workflow/pull/429
=> Update hashes for ufs-weather-model, UFS_UTILS and regional_workflow (remove setting PS1 from regional_workflow/modulefiles/tasks/gaea/*.local)

Externals.cfg
PR #101 was merged before the regional_workflow hash could be updated in `Externals.cfg`. This PR fixes it and points to the head of release/public-v1 of the regional workflow.
=> Follow-up to "Update hashes for ufs-weather-model, UFS_UTILS and regional_workflow"

Externals.cfg, env/wflow_gaea.env
Update gaea workflow environment to avoid using the lua module environment.
Also update `Externals.cfg` temporarily for code review and testing. This change will need to be reverted and the `regional_workflow` hash updated after https://github.com/NOAA-EMC/regional_workflow/pull/440 is merged and before this PR gets merged.
Testing: I tested this successfully on gaea with and without cron:
```
git clone -b gaea_no_lua --recursive https://github.com/climbfuji/ufs-srweather-app
cd ufs-srweather-app
source env/build_gaea_intel.env
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=.. 2>&1 | tee log.cmake
make -j4 2>&1 | tee log.make
cd ..
source env/wflow_gaea.env
#
cd /regional_workflow/ush
./generate_FV3LAM_wflow.sh
############################################################### …
```
=> Update of gaea environment to not use lua modules

Externals.cfg
Update hash for the ufs-weather-model in `Externals.cfg` following the merge of https://github.com/ufs-community/ufs-weather-model/pull/423 and PRs listed in there.
No testing required, the code changes in ccpp-physics are for the CCPP Single Column Model only, the files modified are not used by the ufs-weather-model.
=> release/public-v1: Update hash ufs-weather-model 2021/02/19

Externals.cfg
I made a mistake with the hash in PR #108, this PR fixes it. Tested and works. Will merge immediately. Sorry for the hiccup, and thanks @chan-hoo for reporting.
=> Emergency bugfix following #108: correct hash for ufs-weather-model

Externals.cfg
Update hash of regional_workflow to the latest PR (#[450](https://github.com/NOAA-EMC/regional_workflow/pull/450)) in the regional_workflow repo.
See PR #[450](https://github.com/NOAA-EMC/regional_workflow/pull/450) into regional_workflow.
=> Update hash of regional_workflow

.github/PULL_REQUEST_TEMPLATE
Updated the PR template file (.github/PULL_REQUEST_TEMPLATE) to request the branch name be included in the title and supporting documentation also be included with a PR for new capabilities.
None required
=> Update PR template [to master]

Externals.cfg, docs/UsersGuide/source/Quickstart.rst, env/build_cheyenne_gnu.env
- Update build_cheyenne_gnu.env to use latest hpc stack
- Update Externals.cfg to point to hash of UFS_UTILS with bug fix
- Update Quickstart documentation accordingly
Out-of-the-box case builds and workflow runs to completion on Cheyenne with GNU build.
Intel tests run on Cheyenne and Hera, all with: Workflow status:  SUCCESS
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2 
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
GST_release_public_v1
Documentation has been updated
=> Fix GNU build and run on Cheyenne

Externals.cfg, env/build_hera_intel.env, env/build_orion_intel.env, env/build_wcoss_cray_intel.env, env/build_wcoss_dell_p3_intel.env
- Updated the build environment files `env/build_[machine]_[compiler].env` for Hera, Orion, and WCOSS with the latest hpc-stack.
- Rearranged the module list in alphabetical order for easy maintenance.
- Completed the GST test successfully on Hera, Orion, and WCOSS Dell and Cray.
- Fixes issue mentioned in #137
=> Update build environment files for Hera, Orion, WCOSS with latest hpc-stack

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE
Add dependencies to PR template
Add templates for bug and feature issues.
None required
None required
=> Add issue templates

Externals.cfg, devbuild.sh, env/build_cheyenne_gnu.env, env/build_cheyenne_intel.env, env/build_hera_intel.env, env/build_jet_intel.env, env/build_orion_intel.env, env/wflow_orion.env, src/CMakeLists.txt
This PR (along with https://github.com/NOAA-EMC/regional_workflow/pull/492) update the UFS SRW App to work with a more up-to-date hash of the ufs-weather-model (https://github.com/ufs-community/ufs-weather-model/commit/2f1c8e1883370b30828dea87d4250e10c35499f4)
Ran full suite of tests on Hera (aside from nco tests) with updated environment files (/scratch2/BMC/det/kavulich/workdir/update_app_master/step-by-step/expt_dirs/). The following failures were noted:
- grid_RRFS_AK_13km_RAP_RAP (pre-existing failure, "AVOST IN VILKA")
- grid_RRFS_AK_3km_RAP_RAP (pre-existing failure, "AVOST IN VILKA")
- grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_GSD_SAR (**New failure in make_ics and make_lbcs**)
- grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR (**New failure in make_ics and make_lbcs**)
- …
=> [develop] Update build environments for latest version of weather model (hash 2f1c8e1)
